/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MuzeOto;

import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ozkan
 */
public class Uye_Kaydi extends javax.swing.JFrame {

    /**
     * Creates new form Üye_Kaydı
     */
    public Uye_Kaydi() {
        initComponents();
        
         Toolkit toolkit = getToolkit();
        Dimension dim = toolkit.getScreenSize();
        setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField23 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        adi = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        sifre = new javax.swing.JTextField();
        btn_uye_kaydet = new javax.swing.JButton();
        btn_cikis = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanel1.setLayout(null);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Şifreniz");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(210, 230, 100, 14);

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("ÜYE KAYDI");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(370, 110, 135, 29);
        jPanel1.add(adi);
        adi.setBounds(310, 160, 271, 35);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Uye Kullanıcı Adınız");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(190, 170, 120, 20);
        jPanel1.add(jLabel22);
        jLabel22.setBounds(853, 351, 0, 0);
        jPanel1.add(sifre);
        sifre.setBounds(310, 220, 271, 35);

        btn_uye_kaydet.setBackground(new java.awt.Color(0, 204, 0));
        btn_uye_kaydet.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btn_uye_kaydet.setForeground(new java.awt.Color(255, 255, 255));
        btn_uye_kaydet.setText("Kayıt Ol");
        btn_uye_kaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_uye_kaydetActionPerformed(evt);
            }
        });
        jPanel1.add(btn_uye_kaydet);
        btn_uye_kaydet.setBounds(310, 340, 271, 62);

        btn_cikis.setBackground(new java.awt.Color(255, 51, 51));
        btn_cikis.setText("Geri");
        btn_cikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cikisActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cikis);
        btn_cikis.setBounds(710, 40, 110, 30);

        jButton1.setText("Turlar'ı Gör");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(400, 270, 85, 23);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MuzeOto/resimler/MUZE5.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        jLabel5.setMinimumSize(new java.awt.Dimension(800, 600));
        jLabel5.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel1.add(jLabel5);
        jLabel5.setBounds(-20, 0, 900, 610);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 869, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_uye_kaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_uye_kaydetActionPerformed
        
        try{
            String m=adi.getText().trim();
            String n =sifre.getText().trim();
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/otomasyon3","root","");          
           Statement stmt = con.createStatement();            
            
            
        
                if(m.trim().equals("") || n.trim().equals("")){
                JOptionPane.showMessageDialog(null,"Hatalı Giriş Yapıldı");
                adi.setText("");
                sifre.setText("");
            }
                else
                {
                 String sql ="insert into uyegiris (username,password) values('" + m + "','" + n + "')";  
                 stmt.executeUpdate(sql);
                 JOptionPane.showMessageDialog(null, "Üye Eklendi(gözükmüyorsa yeniden başlatın.)");  
                 con.close();
                 uye_giris ug = new uye_giris();
                 ug.setVisible(true);
                 setVisible(false);
                 
                }
                
                
                
                
                
                }               
        
        catch (HeadlessException | SQLException ex){
            JOptionPane.showMessageDialog(this,"Veritabanına bağlantı sağlanamadı! " + ex.toString());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Uye_Kaydi.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btn_uye_kaydetActionPerformed

    private void btn_cikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cikisActionPerformed
       
        this.dispose();  
        uye_giris ac = new uye_giris();
        ac.setVisible(true);
    }//GEN-LAST:event_btn_cikisActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    TurListe ac = new TurListe();
        ac.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Uye_Kaydi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Uye_Kaydi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Uye_Kaydi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Uye_Kaydi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Uye_Kaydi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adi;
    private javax.swing.JButton btn_cikis;
    private javax.swing.JButton btn_uye_kaydet;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField sifre;
    // End of variables declaration//GEN-END:variables
}
